; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:lilygo-t-display-p4]
board = generic-p4
board_build.partitions = support_files/custom_16Mb_p4.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-display-p4>
build_flags =
	${env.build_flags}
	-Iboards/lilygo-t-display-p4
	-DUSE_SD_MMC=1

# build_src_flags =

	-D BOARD_HAS_SDIO_ESP_HOSTED
	-D BOARD_SDIO_ESP_HOSTED_CLK=12
	-D BOARD_SDIO_ESP_HOSTED_CMD=13
	-D BOARD_SDIO_ESP_HOSTED_D0=11
	-D BOARD_SDIO_ESP_HOSTED_D1=10
	-D BOARD_SDIO_ESP_HOSTED_D2=9
	-D BOARD_SDIO_ESP_HOSTED_D3=8
	-D BOARD_SDIO_ESP_HOSTED_RESET=15

	-D IIC_1_SDA=7
	-D IIC_1_SCL=8

	# SDIO
	-D SDIO_1_CLK=43
	-D SDIO_1_CMD=44
	-D SDIO_1_D0=39
	-D SDIO_1_D1=40
	-D SDIO_1_D2=41
	-D SDIO_1_D3=42

	-D SDIO2_CLK=18
	-D SDIO2_CMD=19
	-D SDIO2_D0=14
	-D SDIO2_D1=15
	-D SDIO2_D2=16
	-D SDIO2_D3=17
	-D SDIO2_RST=GPIO_NUM_NC

	# SD
	## SDMMC
	-D SD_SDIO_CLK=SDIO_1_CLK
	-D SD_SDIO_CMD=SDIO_1_CMD
	-D SD_SDIO_D0=SDIO_1_D0
	-D SD_SDIO_D1=SDIO_1_D1
	-D SD_SDIO_D2=SDIO_1_D2
	-D SD_SDIO_D3=SDIO_1_D3
	## SDSPI
	-D SD_SCLK=SDIO_1_CLK
	-D SD_MOSI=SDIO_1_CMD
	-D SD_MISO=SDIO_1_D0
	-D SD_CS=SDIO_1_D3

	-D ESP32C6_SDIO_CLK=SDIO_2_CLK
	-D ESP32C6_SDIO_CMD=SDIO_2_CMD
	-D ESP32C6_SDIO_D0=SDIO_2_D0
	-D ESP32C6_SDIO_D1=SDIO_2_D1
	-D ESP32C6_SDIO_D2=SDIO_2_D2
	-D ESP32C6_SDIO_D3=SDIO_2_D3

	-DBTN_ACT=LOW
	-DSEL_BTN=0
	-DUP_BTN=-1
	-DDW_BTN=-1

	-D TFT_DSI_PANEL=1
	;-D USE_CANVAS=1
	-D ROTATION=0
	-D TFT_IPS=1
	-D TFT_COL_OFS1=0
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS1=0
	-D TFT_ROW_OFS2=0
	# Definitions for TFT
	-D TFT_DATABUS_N=4
	-D TFT_HSYNC_PULSE_WIDTH=28
	-D TFT_HSYNC_BACK_PORCH=26
	-D TFT_HSYNC_FRONT_PORCH=20
	-D TFT_VSYNC_PULSE_WIDTH=2
	-D TFT_VSYNC_BACK_PORCH=22
	-D TFT_VSYNC_FRONT_PORCH=200
	-D TFT_PREF_SPEED=60000000

	-D TFT_DISPLAY_DRIVER_N=50
	-D TFT_WIDTH=540
	-D TFT_HEIGHT=1168
	-D TFT_RST=-1
	-D TFT_DSI_INIT=hi8561_lcd_init


	# Definitions for AMOLED
	;-D TFT_DATABUS_N=4
	;-D TFT_HSYNC_PULSE_WIDTH=50
	;-D TFT_HSYNC_BACK_PORCH=150
	;-D TFT_HSYNC_FRONT_PORCH=50
	;-D TFT_VSYNC_PULSE_WIDTH=40
	;-D TFT_VSYNC_BACK_PORCH=120
	;-D TFT_VSYNC_FRONT_PORCH=80
	;-D TFT_PREF_SPEED=60000000

	;-D TFT_DISPLAY_DRIVER_N=50
	;-D TFT_WIDTH=568
	;-D TFT_HEIGHT=1232
	;-D TFT_RST=-1
	;-D TFT_DSI_INIT=rm69a10_lcd_init_cmd

;lib_deps =
;	https://github.com/Xinyuan-LilyGO/lilygo_device_driver
