; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:lilygo-t-display-S3-amoled]
board = lilygo-t-display-s3-pro
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-display-s3-amoled>
build_src_flags =
	-DDISABLE_OTA

    -DROTATION=3 # Portrait, 3 to landscape
	-DHAS_1_BUTTON=1
    -DSEL_BTN=0
	-DBTN_ACT=LOW
	-DBTN_ALIAS='"Sel"'
	-DLED=-1
	-DLED_ON=HIGH

	-DFP=1
	-DFM=2
	-DFG=3

	-DHAS_TOUCH=1

	;TFT_eSPI display
	-DDRIVER_RM67162     		# Configure all registers
	-D TFT_QSPI=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=536

	-D TFT_CS=6
	-D TFT_SCLK=47
	-D TFT_D0=18
	-D TFT_D1=7
	-D TFT_D2=48
	-D TFT_D3=5
	-D TFT_RST=17
	-D TFT_IPS=0

	;dummy vals
	-D TFT_COL_OFS1=0
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=0

	-DSDCARD_CS=11
	-DSDCARD_SCK=14
	-DSDCARD_MISO=13
	-DSDCARD_MOSI=12

