; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:Marauder-v8]
board = esp32-c5-devkitc-1
board_build.partitions = support_files/custom_8Mb2.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-v8>
build_flags =
	${env.build_flags}
	-Iboards/marauder-v8
	-DDONT_USE_INPUT_TASK=1
	-DOTA_TAG='"marauder-v8"'

	-DMARAUDERV8=1

	;-DPART_04MB=1
	-DPART_08MB=0
	;-DPART_16MB=0

    -DROTATION=0
    -DHAS_BTN=0
    -DSEL_BTN=-1
	-DUP_BTN=-1
	-DDW_BTN=-1
	-DBTN_ACT=LOW
	-DBTN_ALIAS='"Sel"'
	-DLED=4
	-DLED_ON=LOW

	-DFP=1
	-DFM=2
	-DFG=3

	-DHAS_TOUCH=1
	-DILI9341_DRIVER=1
	-DTFT_MISO=2
	-DTFT_MOSI=7
	-DTFT_SCLK=6
	-DTFT_CS=23
	-DTFT_DC=24
	-DTFT_RST=-1
	-DTFT_BL=25
	-DTOUCH_CS=1

	-D GFX_BL=32
	-D TFT_IPS=0
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_COL_OFS1=0
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=0

	-DSDCARD_CS=10
	-DSDCARD_SCK=TFT_SCLK
	-DSDCARD_MISO=TFT_MISO
	-DSDCARD_MOSI=TFT_MOSI

	-D HAS_RESISTIVE_TOUCH=1
	-D CYD28_TouchR_IRQ=-1
	-D CYD28_TouchR_MISO=TFT_MISO
	-D CYD28_TouchR_MOSI=TFT_MOSI
	-D CYD28_TouchR_CSK=TFT_SCK
	-D CYD28_TouchR_CS=1

	-DTFT_BRIGHT_CHANNEL=0
	-DTFT_BRIGHT_Bits=8
	-DTFT_BRIGHT_FREQ=5000

lib_ignore =
	SensorLib
	XPowersLib
